spring.application.name=BookStore
server.port=${PORT:1100}
spring.datasource.name = book
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/book?ServerTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:weirdo@620}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update 